export interface ProcessEntry {
  author: string;
  cropId: number;
  day: number;
  date:  string;
  time: string;
  hay?: number;
  corn?: number;
  guano?:number;
  cottonSeedCake?: number;
  soybeanMeal?: number;
  gypsum?: number;
  urea?: number;
  ammoniumSulphate?: number;
  activities?: string;
  temperature?: number;
  comment?: string;
  thermocoupleOne?: number;
  thermocoupleTwo?: number;
  thermocoupleThree?: number;
  averageThermocouple?: number;
  roomTemperature?: number;
  growRoom?: number;
  motorFrequency?: number;
  freshAir?: number;
  recirculation?: number;
  airTemperature?: number;
  compostTemperature?: string;
  carbonDioxide?: number;
  airHumidity?: number;
  setting?: number;
  cropPhase?: string;
  [key: string]: any;
}
