export interface ProcessEntry {
  author: string;
  crop_id: number;
  day: number;
  date:  string;
  time: string;
  hay?: number;
  corn?: number;
  guano?:number;
  cottonSeedCake?: number;
  soybeanMeal?: number;
  gypsum?: number;
  urea?: number;
  ammoniumSulphate?: number;
  activities?: string;
  temperature?: number;
  comment?: string;
  t1?: number;
  t2?: number;
  t3?: number;
  tp?: number;
  ta?: number;
  growRoom?: number;
  frequency?: number;
  freshAir?: number;
  recirculation?: number;
  airTemperature?: number;
  compostTemperature?: string;
  carbonDioxide?: number;
  airHydrogen?: number;
  setting?: number;
  processType?: string;
  [key: string]: any;
}
